- name: install master
  hosts: master
  become: true
  gather_facts: yes  
  tasks:
    - debug: msg="{{ ansible_facts.enp3s0.ipv4.address }}"	
  roles:
    - base_linux
    - create-sshkey
    - java
    - jenkins
    - remote-agent
    - apache_httpd    
    #- create_tls_certs
    - download_certs    

- name: start jenkins and apache
  hosts: master
  become: true
  tasks:
  - name: restart jenkins
    service: name=jenkins state=restarted
  
  - name: restart apache2
    service: name=apache2 state=restarted

    
- name: copy ssh-key  from /vagrant/keys  to /root/.ssh
  hosts: all
  become: true
  roles:
    - role: remote-sshd
      when: ansible_facts.virtualization_type == "virtualbox"


- name: install ssh-key & install docker
  hosts: all
  become: true
  roles:
    - docker
    - kubernetes
    - java

  tasks:
  - name: jenkins password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_pw
  - debug: msg="initialAdminPassword = {{ jenkins_pw.stdout_lines }}"
