- name: create ssh-key
  hosts: master
  become: true
  roles:
    - create-sshkey

- name: copy ssh-key & install docker
  hosts: all
  become: true
  roles:
    - remote-sshd
    - docker
    
- name: install jenkins
  hosts: master
  gather_facts: true
  become: true
  roles:
    - jenkins
    - kubernetes    

