- name: install master
  hosts: master
  become: true
  roles:
    - base_linux  
    - create-sshkey
    - java
    - jenkins
    - remote-agent

- name: copy ssh-key  from /vagrant/keys  to /root/.ssh
  hosts: all
  become: true
  roles:
    - role: remote-sshd
      when: ansible_facts.virtualization_type == "virtualbox"
    
- name: install ssh-key & install docker
  hosts: all
  become: true
  roles:
    - docker
    - kubernetes
    - java

  tasks:
  - name: jenkins password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_pw
  - debug: msg="initialAdminPassword = {{ jenkins_pw.stdout_lines }}"
