- name: install master
  hosts: master
  become: true
  roles:
    - create-sshkey
    - java
    - jenkins
    - remote-agent
    
- name: install ssh-key & install docker
  hosts: all
  become: true
  roles:
    - remote-sshd
    - docker
    - kubernetes
    - java



