- name: Configure HTTPS Access 
  file:
    path: "{{ ca_dir }}"
    state: directory

- name: Download CA pem
  shell: |
    curl -k -O -L https://{{ ca_ip }}/ca.pem
    cp ca.pem /etc/ssl/certs/labo_local_ca.pem
  args:
    chdir: "{{ ca_dir }}"


- name: Download Jenkins ssl certs
  shell: |
    curl -k -O -L https://{{ ca_ip }}/{{ domain }}/{{ domain }}.crt
    curl -k -O -L https://{{ ca_ip }}/{{ domain }}/{{ domain }}.key
  args:
    chdir: "{{ ca_dir }}"


- name: Download Jenkins ssl certs
  shell: |
    mkdir -p {{ dst_dir }}/ssl
    cp {{ domain }}.crt  {{ dst_dir }}/ssl/{{ domain }}.cert
    cp {{ domain }}.key  {{ dst_dir }}/ssl/{{ domain }}.key
    cp ca.pem {{ dst_dir }}/ssl/labo_local_ca.pem
  args:
    chdir: "{{ ca_dir }}"


- debug: msg="virtualization_type = {{ ansible_facts.virtualization_type }}"
  
- shell: |
    cp {{ domain }}.cert /vagrant/{{ domain }}.cert
    cp {{ domain }}.key  /vagrant/{{ domain }}.key
    cp ca.crt /vagrant/ca.crt
  args:
    chdir: "{{ ca_dir }}"
  when: ansible_facts.virtualization_type == "virtualbox"

