#- name: Configure HTTPS Access 
#  file:
#    path: "{{ ca_dir }}"
#    state: directory

#
# プライベートCA証明書の取得
#
- name: Download CA pem
  get_url:
    url: "https://{{ ca_ip }}/ca.pem"
    dest: /etc/ssl/certs/labo_local_ca.pem
    validate_certs: no
    mode: 0440

#- name: Download CA pem
#  shell: |
#    curl -k -O -L https://{{ ca_ip }}/ca.pem
#    cp ca.pem /etc/ssl/certs/labo_local_ca.pem
#  args:
#    chdir: "{{ ca_dir }}"
#
#- name: Download Jenkins ssl certs
#  shell: |
#    curl -k -O -L https://{{ ca_ip }}/{{ domain }}/{{ domain }}.crt
#    curl -k -O -L https://{{ ca_ip }}/{{ domain }}/{{ domain }}.key
#  args:
#    chdir: "{{ ca_dir }}"
#
#- name: Download Jenkins ssl certs
#  shell: |
#    mkdir -p {{ dst_dir }}/ssl
#    cp {{ domain }}.crt  {{ dst_dir }}/ssl/{{ domain }}.cert
#    cp {{ domain }}.key  {{ dst_dir }}/ssl/{{ domain }}.key
#    cp ca.pem {{ dst_dir }}/ssl/labo_local_ca.pem
#  args:
#    chdir: "{{ ca_dir }}"

#
# ウェブサイト用の証明書の取得
#
- name: mkdir dest dir
  file:
    path: "{{ dst_dir }}"
    state: directory

- name: Download Web-Site SSL Certs
  get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.crt"
    dest: "{{ dst_dir }}/{{ fqdn }}.cert"
    validate_certs: no
    mode: 0440
- get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.key"
    dest: "{{ dst_dir }}/{{ fqdn }}.key"
    validate_certs: no
    mode: 0440


#- debug: msg="virtualization_type = {{ ansible_facts.virtualization_type }}"
#  
#- shell: |
#    cp {{ domain }}.cert /vagrant/{{ domain }}.cert
#    cp {{ domain }}.key  /vagrant/{{ domain }}.key
#    cp ca.crt /vagrant/ca.crt
#  args:
#    chdir: "{{ ca_dir }}"
#  when: ansible_facts.virtualization_type == "virtualbox"

