##  Jenkins のインストール
- name: Add Jenkins GPG key
  shell: |
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    echo 'deb https://pkg.jenkins.io/debian-stable binary/' | tee -a /etc/apt/sources.list    

- name: ensure the jenkins apt repository key is installed
  apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
  become: yes

- name: ensure the repository is configured
  apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  become: yes

- shell: |
    apt list -a jenkins
  
- name: ensure jenkins is installed
  apt: name=jenkins={{ jenkins_version }} update_cache=yes
  become: yes

#- name: ensure jenkins is running
#  service: name=jenkins state=started

