- name: mkdir .ssh directory
  file:
    path: "{{ home_path }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

    
- name: Copy shared_fs keys to id_rsa.pub 
  command: cp /vagrant/keys/id_rsa.pub "{{ home_path }}/id_rsa.pub"
- file:
    path: "{{ home_path }}/id_rsa.pub"
    owner: jenkins
    group: jenkins
    mode: '0444'
- name: Copy shared_fs/keys to id_rsa 
  command: cp /vagrant/keys/id_rsa "{{ home_path }}/id_rsa"
- file:
    path: "{{ home_path }}/id_rsa"
    owner: jenkins
    group: jenkins
    mode: '0400'

- name: Create authorized_keys
  command: cp /vagrant/keys/id_rsa.pub "{{ home_path }}/authorized_keys"
- file:
    path:  "{{ home_path }}/authorized_keys"
    owner: jenkins
    group: jenkins
    mode: '0400'

  

     


